### ISSUE TITLE
[object Error] app.js:85

### ISSUE THREAD

**Issue by Mte90** [gdilella/Keefox#16]
I get this error when i try to open my file.
The file referenced for the error is kdbx.js at the line 100. execute in the app.js file at line 82.

**Comment by marcoscarpetta** [comment]
I'm not getting this error. @giammyjet you?
@Mte90 the last code should give you more informations about the error.

**Comment by Mte90** [comment]
Same error with two different file.
I've tried the 1.0 version on this repo and the problem not exists.

**Comment by marcoscarpetta** [comment]
I'm getting the error when there are entries in sub-groups and not only in the main group.

**Comment by Mte90** [comment]
Uhm i have all sub groups with subgroups and entries so the problem can be this.
One minute for download and test :-P

**Comment by Mte90** [comment]
uhm same error :-(

**Comment by marcoscarpetta** [comment]
With the last commit I don't get more the error

**Comment by Mte90** [comment]
The organization of a file that create the error
![screenshot](http://i.imgur.com/MW6xwOa.png)

**Comment by marcoscarpetta** [comment]
@Mte90 can you try now?
I'm using the first code again.

**Comment by Mte90** [comment]
Yes now work!!!!
