### ISSUE TITLE
Animation missing in the list

### ISSUE THREAD

**Issue by Mte90** [gdilella/Keefox#17]
After the generation of the list the animation of switching of drawer is missing in the lists.

**Comment by marcoscarpetta** [comment]
I can add another section like that with id "details" and animate the switching between groups, subgroups and entries, but I don't know if this is the best way to do it.

**Comment by Mte90** [comment]
I think that the better solution it's use the data-position and add on the click the effect, in this way youdon't have to insert many lines of code.
