### ISSUE TITLE
Flash on the about page during transition to password page

### ISSUE THREAD

**Issue by marcoscarpetta** [gdilella/Keefox#18]
I see a flash showing the about page while switching to the password insert page. This is due to the focus on the password entry and can be easily fixed. Do you also get this bug?

**Comment by gdilella** [comment]
i don't get it.
can you show me some screen?

**Comment by marcoscarpetta** [comment]
I was getting this on my phone with the 2.0 pre-release. I'm not getting it on the 1.3 simulator.
