### ISSUE TITLE
Freezing after tap on Done

### ISSUE THREAD

**Issue by Mte90** [gdilella/Keefox#2]
After a tap on done (after the password request) the app freezing.
I think that show a spinner it's better :-)

**Comment by gdilella** [comment]
closed

**Comment by Mte90** [comment]
Uhm in some case the spinner it's not showed.

**Comment by gdilella** [comment]
can you explain more?

**Comment by Mte90** [comment]
The app freeze but the spinner it's not showed or the spinner it's freezed.
i use my keepass file that are "big" 11kb of size.

**Comment by marcoscarpetta** [comment]
@Mte90 can you try now?
