### ISSUE TITLE
Better interface

### ISSUE THREAD

**Issue by Mte90** [gdilella/Keefox#4]
I think that a list for show all the content of the kdbx file it's bad for navigate.
See the KeePassX software for copy the tree of the groups with the password.
Also the Keepassdroid app for android

**Comment by marcoscarpetta** [comment]
I can do a list of clickable items containing titles and a details page.

**Comment by gdilella** [comment]
so, @marcoscarpetta i can assign this issue to you?
i have to do the multilanguage system (issue #3)

**Comment by marcoscarpetta** [comment]
@giammyjet ok!

**Comment by Mte90** [comment]
this pull it's not enough for me.
In the list i have the content and after the description.
Example:
pass1234556
password
Mysite.tld
title

Also if the field notes it's empty, hide it!

Also i think that the domain (it's not mandatory) of the data it's not useful in the list and in the title.

The last also the interface not reconized the groups that the kdbx support. 
I get a long list of all my password but i have created the groups for a better organization :-)

**Comment by gdilella** [comment]
@marcoscarpetta, when this issue is finally closed, please notice me

**Comment by marcoscarpetta** [comment]
Implementing groups support is more difficult because I have to edit the kdbx.js file, so I think we should close this issue and open a new one to implement groups.

**Comment by gdilella** [comment]
ok. close
