### ISSUE TITLE
Implement Groups

### ISSUE THREAD

**Issue by gdilella** [gdilella/Keefox#9]

**Comment by Mte90** [comment]
At the moment it's possible add a line for separate the various groups in the list?

**Comment by marcoscarpetta** [comment]
No

**Comment by marcoscarpetta** [comment]
Do you think there is any other thing to do or we can close?

**Comment by Mte90** [comment]
Perfect now :-D
i have only a doubt for the icon that have not the ffos style but it's not a important problem :-)
